{ ... }:

{
  imports = [
    ./acsm.nix
    ./anduin.nix
    ./anduin-postgres.nix
    ./arr.nix
    ./audiobookshelf.nix
    ./blocky.nix
    ./bookorbit.nix
    ./caddy.nix
    ./calibre-news.nix
    ./calibre-web.nix
    ./chaptarr.nix
    ./frigate.nix
    ./grafana.nix
    ./headache-sync.nix
    ./hermes.nix
    ./immich.nix
    ./jellyfin.nix
    ./keepalived.nix
    ./liftosaur-sync.nix
    ./linkwarden.nix
    ./miniflux.nix
    ./mosquitto.nix
    ./netalertx.nix
    ./ollama.nix
    ./openwebui.nix
    ./pocket-id.nix
    ./postgres.nix
    ./prometheusExporter.nix
    ./alloy.nix
    ./restic.nix
    ./tandoor.nix
    ./withings-sync.nix
    ./zigbee2mqtt.nix
  ];
}
