[repository]
repository = "/backup"
password-file = "/run/agenix/restic-password"
no-cache = true

[forget]
keep-daily = 14
keep-weekly = 4

[backup]
exclude-if-present = [".nobackup", "CACHEDIR.TAG"]

