{
 "title": "blocky",
 "description": "Dashboard for blocky - Fast and lightweight DNS proxy as ad-blocker for local network with many features",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(up{job=~\"blocky.*\"}, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "State",
   "type": "stat",
   "description": "current service state",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Blocking",
   "type": "stat",
   "description": "Is blocking enabled?",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blocky_blocking_enabled{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "Blocky [version](https://github.com/0xERR0R/blocky) number",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blocky_build_info{job=~\"$job\"} "
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "stat",
   "description": "Average query response time for all query types",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(blocky_request_duration_seconds_sum{job=~\"$job\"}[$__range])) / sum(increase(blocky_request_duration_seconds_count{job=~\"$job\"}[$__range]))) * 1000"
    }
   ]
  },
  {
   "title": "Blacklist entries total",
   "type": "stat",
   "description": "Number of blacklist entries",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(blocky_denylist_cache_entries{job=~\"$job\"}) / sum(up{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Memory allocated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_sys_bytes{job=~\"$job\"})/sum(up{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Queries blocked",
   "type": "stat",
   "description": "Percentage of blocked queries",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_response_total{job=~\"$job\", response_type=\"BLOCKED\"}[$__range])) / sum(increase(blocky_query_total{job=~\"$job\"}[$__range])) "
    }
   ]
  },
  {
   "title": "Query Count Total",
   "type": "stat",
   "description": "Number of all queries. Shows the last value",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(blocky_query_total{job=~\"$job\"}[$__range]))) "
    }
   ]
  },
  {
   "title": "Cache entries count",
   "type": "stat",
   "description": "Number of entries in the cache. Shows the last value",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "blocky_cache_entries{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Cache Hit/Miss ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_cache_hits_total{job=~\"$job\"}[$__range])) / (sum(increase(blocky_cache_hits_total{job=~\"$job\"}[$__range])) + sum(increase(blocky_cache_misses_total{job=~\"$job\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Error count",
   "type": "stat",
   "description": "Number of occured errors",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(blocky_error_total{job=~\"$job\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Prefetch count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(increase(blocky_prefetches_total{job=~\"$job\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Prefetch rate per min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(blocky_prefetches_total{job=~\"$job\"}[5m])) * 60"
    }
   ]
  },
  {
   "title": "Prefetch domain count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "blocky_prefetch_domain_name_cache_entries{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Last list refresh",
   "type": "stat",
   "description": "Time since last list refresh",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() -blocky_last_list_group_refresh_timestamp_seconds{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "avg requests / min" }
   ],
   "targets": [
    {
     "expr": "sum(rate(blocky_query_total{job=~\"$job\"}[5m])) * 60",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Request rate per client",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "avg requests / min" }
   ],
   "targets": [
    {
     "expr": "sum by (client) (rate(blocky_query_total{job=~\"$job\"}[5m])) * 60",
     "legendFormat": " {{client}}"
    }
   ]
  },
  {
   "title": "request duration (upstream)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(increase(blocky_request_duration_seconds_bucket{job=~\"$job\", response_type=\"RESOLVED\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Query by type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": " sort_desc(sum by (type) (ceil(increase(blocky_query_total{job=~\"$job\"}[$__range]))))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Query per Client",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum by (client) (ceil(increase(blocky_query_total{job=~\"$job\"}[$__range]))))",
     "legendFormat": "{{ client }}"
    }
   ]
  },
  {
   "title": "Blacklist by group",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(1, blocky_denylist_cache_entries{job=~\"$job\"}) by (group)",
     "legendFormat": "{{ group }}"
    }
   ]
  },
  {
   "title": "Response Reasons",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": " sort_desc(sum by (reason) (ceil(increase(blocky_response_total{job=~\"$job\"}[$__range]))))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Response Type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": " sort_desc(sum by (response_type) (ceil(increase(blocky_response_total{job=~\"$job\"}[$__range]))))",
     "legendFormat": "{{response_type}}"
    }
   ]
  },
  {
   "title": "Response status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": " sort_desc(sum by (response_code) (ceil(increase(blocky_response_total{job=~\"$job\"}[$__range]))))",
     "legendFormat": "{{response_code}}"
    }
   ]
  }
 ]
}