{
 "title": "Miniflux",
 "refresh": "30s",
 "panels": [
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "miniflux_users", "legendFormat": "Users" }
   ]
  },
  {
   "title": "Feeds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "miniflux_feeds{status='total'}", "legendFormat": "Feeds" }
   ]
  },
  {
   "title": "Entries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "miniflux_entries{status='total'}",
     "legendFormat": "Entries"
    }
   ]
  },
  {
   "title": "Broken Feeds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "miniflux_broken_feeds", "legendFormat": "Broken" }
   ]
  },
  {
   "title": "DB Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    { "expr": "miniflux_db_open_connections", "legendFormat": "Open" },
    { "expr": "miniflux_db_connections_in_use", "legendFormat": "In Use" }
   ]
  }
 ]
}